#!/bin/bash
#cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w ${1:-32} | head -n 1
#git rev-parse --short HEAD
#cat /dev/urandom | tr -dc "a-zA-Z0-9!@#$%^&*()_+?><~\`;'" | fold -w 32 | head -n 1
cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1